[workspace]
channels = ["conda-forge"]
name = "research"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipywidgets = ">=8.1.7,<9"

[pypi-dependencies]
jax = { version = ">=0.7.1, <0.8", extras = ["cuda12"] }
flax = ">=0.11.2, <0.12"
ipykernel = ">=6.30.1, <7"
librosa = ">=0.11.0, <0.12"
grain = ">=0.2.12, <0.3"
tqdm = ">=4.67.1, <5"
tensorboard = ">=2.20.0, <3"
xprof = ">=2.20.6, <3"
pandas = ">=2.3.2, <3"
jiwer = ">=4.0.0, <5"
clu = ">=0.0.12, <0.0.13"
tensorflow = ">=2.20.0, <3"
