#!/usr/bin/env python
"""Emit the files the on-device C runner needs alongside the .nb.

The board has no Python, so everything the runtime depends on has to be either
a flat binary it can fread() or a constant compiled into the binary:

    filterbank.bin      float32 mel filterbank, n_mels x (n_fft/2+1), row major
    vocab.txt           one token per line, UTF-8, in token-id order
    tinyvoice_model.h   shapes and the fixed-point scales the .nb expects

The fixed-point scales come from nbg_meta.json, which the toolkit writes when
it packs the network binary -- the .nb takes pre-quantised int16 at its inputs,
so the runner has to know the exponent for each tensor.

    python scripts/export_device_assets.py --qtype int16
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from conformer.npu_runtime import Artifacts  # noqa: E402


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model-dir", type=Path, default=Path("artifacts/npu/tinyvoice"))
    p.add_argument("--qtype", default="int16")
    p.add_argument("--out", type=Path, default=None, help="default <model-dir>/device")
    args = p.parse_args()

    artifacts = Artifacts(args.model_dir)
    meta = artifacts.meta
    out = args.out or (args.model_dir / "device")
    out.mkdir(parents=True, exist_ok=True)

    nbg_path = args.model_dir / f"{artifacts.name}_{args.qtype}_nbg_meta.json"
    if not nbg_path.exists():
        raise SystemExit(
            f"{nbg_path} not found -- run scripts/npu_convert.sh so the toolkit "
            f"emits the network binary's tensor metadata"
        )
    nbg = json.loads(nbg_path.read_text())

    def fixed_point(section: str, name: str) -> int:
        for entry in nbg[section].values():
            if entry["name"].split("/")[0] == name:
                if entry["quantize"]["qtype"] != "i16":
                    raise SystemExit(
                        f"{name} is {entry['quantize']['qtype']}; the device runner "
                        f"assumes int16 -- convert with qtype int16 or extend it"
                    )
                return int(entry["quantize"]["fl"])
        raise SystemExit(f"no tensor named {name} in {nbg_path}")

    mel_fl = fixed_point("Inputs", "mel")
    mask_fl = fixed_point("Inputs", "mask")
    logits_fl = fixed_point("Outputs", "attach_logits")

    filterbank = np.asarray(artifacts.filterbank, dtype=np.float32)
    (out / "filterbank.bin").write_bytes(filterbank.tobytes())

    # One token per line. Tokens are single characters (possibly a space), so
    # only the trailing newline is a separator -- the reader must not strip.
    vocab = meta["vocab"]
    (out / "vocab.txt").write_text("\n".join(vocab) + "\n", encoding="utf-8")

    header = f"""/* Generated by scripts/export_device_assets.py -- do not edit.
 * Model: {artifacts.name}, checkpoint step {meta['checkpoint_step']}, {args.qtype}.
 */
#ifndef TINYVOICE_MODEL_H
#define TINYVOICE_MODEL_H

#define TV_SAMPLE_RATE   {meta['sampling_rate']}
#define TV_WINDOW_SAMPLES {meta['window_samples']}   /* {meta['window_seconds']:.2f} s */
#define TV_N_FFT         {meta['n_fft']}
#define TV_WIN_LENGTH    {meta['win_length']}
#define TV_HOP_LENGTH    {meta['hop_length']}
#define TV_N_MELS        {meta['n_mels']}
#define TV_N_FREQ        {meta['n_fft'] // 2 + 1}
#define TV_MEL_FRAMES    {meta['mel_frames']}
#define TV_SEQ_LEN       {meta['seq_len']}
#define TV_VOCAB_SIZE    {meta['vocab_size']}
#define TV_BLANK_ID      {meta['blank_id']}
#define TV_PAD_ID        {meta['pad_id']}

/* Dynamic fixed point exponents the .nb expects/produces: value = q / 2^fl. */
#define TV_MEL_FL        {mel_fl}
#define TV_MASK_FL       {mask_fl}
#define TV_LOGITS_FL     {logits_fl}

#endif
"""
    (out / "tinyvoice_model.h").write_text(header)

    print(f"device assets -> {out}")
    print(f"  filterbank.bin     {filterbank.shape} float32")
    print(f"  vocab.txt          {len(vocab)} tokens")
    print(f"  tinyvoice_model.h  mel fl={mel_fl}, mask fl={mask_fl}, logits fl={logits_fl}")


if __name__ == "__main__":
    main()
